# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone_swarm.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'drone_swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64rone_swarm.proto\x12\x0b\x64rone_swarm\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"7\n\x0b\x45ulerAngles\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"\xd9\x01\n\x10TelemetryRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\x12*\n\x08\x61ttitude\x18\x05 \x01(\x0b\x32\x18.drone_swarm.EulerAngles\x12\x15\n\rbattery_level\x18\x06 \x01(\x02\x12&\n\x08velocity\x18\x07 \x01(\x0b\x32\x14.drone_swarm.Vector3\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\"5\n\x11TelemetryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\"\xf3\x01\n\x0f\x43ommandResponse\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12-\n\x0ftarget_velocity\x18\x02 \x01(\x0b\x32\x14.drone_swarm.Vector3\x12-\n\x0ftarget_position\x18\x03 \x01(\x0b\x32\x14.drone_swarm.Vector3\x12\x18\n\x10separation_force\x18\x04 \x01(\x02\x12\x17\n\x0f\x61lignment_force\x18\x05 \x01(\x02\x12\x16\n\x0e\x63ohesion_force\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x12\n\ncommand_id\x18\x08 \x01(\t2\xb6\x01\n\x10TelemetryService\x12N\n\rSendTelemetry\x12\x1d.drone_swarm.TelemetryRequest\x1a\x1e.drone_swarm.TelemetryResponse\x12R\n\x0fStreamTelemetry\x12\x1d.drone_swarm.TelemetryRequest\x1a\x1c.drone_swarm.CommandResponse(\x01\x30\x01\x32\xa8\x01\n\x0e\x43ommandService\x12G\n\nGetCommand\x12\x1b.drone_swarm.CommandRequest\x1a\x1c.drone_swarm.CommandResponse\x12M\n\x0eStreamCommands\x12\x1b.drone_swarm.CommandRequest\x1a\x1c.drone_swarm.CommandResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=34
  _globals['_VECTOR3']._serialized_end=76
  _globals['_EULERANGLES']._serialized_start=78
  _globals['_EULERANGLES']._serialized_end=133
  _globals['_TELEMETRYREQUEST']._serialized_start=136
  _globals['_TELEMETRYREQUEST']._serialized_end=353
  _globals['_TELEMETRYRESPONSE']._serialized_start=355
  _globals['_TELEMETRYRESPONSE']._serialized_end=408
  _globals['_COMMANDREQUEST']._serialized_start=410
  _globals['_COMMANDREQUEST']._serialized_end=444
  _globals['_COMMANDRESPONSE']._serialized_start=447
  _globals['_COMMANDRESPONSE']._serialized_end=690
  _globals['_TELEMETRYSERVICE']._serialized_start=693
  _globals['_TELEMETRYSERVICE']._serialized_end=875
  _globals['_COMMANDSERVICE']._serialized_start=878
  _globals['_COMMANDSERVICE']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
