# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import drone_swarm_pb2 as drone__swarm__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drone_swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTelemetry = channel.unary_unary(
                '/drone_swarm.TelemetryService/SendTelemetry',
                request_serializer=drone__swarm__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=drone__swarm__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.stream_stream(
                '/drone_swarm.TelemetryService/StreamTelemetry',
                request_serializer=drone__swarm__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=drone__swarm__pb2.CommandResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTelemetry,
                    request_deserializer=drone__swarm__pb2.TelemetryRequest.FromString,
                    response_serializer=drone__swarm__pb2.TelemetryResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=drone__swarm__pb2.TelemetryRequest.FromString,
                    response_serializer=drone__swarm__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone_swarm.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone_swarm.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone_swarm.TelemetryService/SendTelemetry',
            drone__swarm__pb2.TelemetryRequest.SerializeToString,
            drone__swarm__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/drone_swarm.TelemetryService/StreamTelemetry',
            drone__swarm__pb2.TelemetryRequest.SerializeToString,
            drone__swarm__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CommandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCommand = channel.unary_unary(
                '/drone_swarm.CommandService/GetCommand',
                request_serializer=drone__swarm__pb2.CommandRequest.SerializeToString,
                response_deserializer=drone__swarm__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamCommands = channel.unary_stream(
                '/drone_swarm.CommandService/StreamCommands',
                request_serializer=drone__swarm__pb2.CommandRequest.SerializeToString,
                response_deserializer=drone__swarm__pb2.CommandResponse.FromString,
                _registered_method=True)


class CommandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommand,
                    request_deserializer=drone__swarm__pb2.CommandRequest.FromString,
                    response_serializer=drone__swarm__pb2.CommandResponse.SerializeToString,
            ),
            'StreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=drone__swarm__pb2.CommandRequest.FromString,
                    response_serializer=drone__swarm__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone_swarm.CommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone_swarm.CommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone_swarm.CommandService/GetCommand',
            drone__swarm__pb2.CommandRequest.SerializeToString,
            drone__swarm__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/drone_swarm.CommandService/StreamCommands',
            drone__swarm__pb2.CommandRequest.SerializeToString,
            drone__swarm__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
